export default [
  { actorId: "12dsa3", actorName: "Ravindu" },
  { actorId: "12vfd3", actorName: "Manoj" },
  { actorId: "25sfr5", actorName: "Chathuranga" },
  { actorId: "98gdv4", actorName: "Tharindu" },
  { actorId: "51fsr3", actorName: "Kavisha" },
  { actorId: "nb563d", actorName: "Isuru" },
  { actorId: "2wslm4", actorName: "Pasan" },
  { actorId: "9uh67s", actorName: "Hashan" },
  { actorId: "67rf34", actorName: "Thanuja" },
  { actorId: "b3g4h4", actorName: "Chathura" },
  { actorId: "3eud6f", actorName: "Shalika" },
  { actorId: "mn234d", actorName: "Minoj" },
  { actorId: "9df45f", actorName: "Hasindu" },
  { actorId: "i45rfg", actorName: "Raveena" },
  { actorId: "n2wj4d", actorName: "Shakila" },
  { actorId: "9zxxsw", actorName: "Sumudu" },
  { actorId: "okjfd4", actorName: "Nuwan" },
  { actorId: "mnjnd3", actorName: "Sudesh" },
  { actorId: "8uusdc", actorName: "Vimukthi" },
  { actorId: "9iddn3", actorName: "Malinda" },
  { actorId: "jk23d4", actorName: "Sahan" },
  { actorId: "8edj32", actorName: "Pradeep" },
];
