export const PREFIX = "@@actors/";

export const ASYNC_ACTORS_INIT = `${PREFIX}ASYNC_ACTORS_INIT`;
export const INITIALIZE_ACTORS = `${PREFIX}INITIALIZE_ACTORS`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_ALL_ACTORS_SUCCESS = `${PREFIX}GET_ALL_ACTORS_SUCCESS`;
export const ON_ADD_FREE_DATE = `${PREFIX}ON_ADD_FREE_DATE`;
