export const PREFIX = "@@auth/";

export const ASYNC_AUTH_INIT = `${PREFIX}ASYNC_AUTH_INIT`;
export const INITIALIZE_AUTH_INIT = `${PREFIX}INITIALIZE_AUTH_INIT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const ADD_NEW_SCRIPT_SUCCESS = `${PREFIX}ADD_NEW_SCRIPT_SUCCESS`;
export const ON_SAVE_SCRIPT_DATA = `${PREFIX}ON_SAVE_SCRIPT_DATA`;
export const ON_SAVE_INVENTORY_DATA = `${PREFIX}ON_SAVE_INVENTORY_DATA`;
export const SET_INITIAL_SCRIPTS = `${PREFIX}SET_INITIAL_SCRIPTS`;
