export const PREFIX = "@@inventory/";

export const ASYNC_INVENTORY_INIT = `${PREFIX}ASYNC_INVENTORY_INIT`;
export const INITIALIZE_INVENTORY = `${PREFIX}INITIALIZE_INVENTORY`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_ALL_INVENTORY_SUCCESS = `${PREFIX}GET_ALL_INVENTORY_SUCCESS`;
export const ON_CHANGE_INVENTORY_FIELD = `${PREFIX}ON_CHANGE_INVENTORY_FIELD`;
export const ON_ADD_NEW_INVENTORY = `${PREFIX}ON_ADD_NEW_INVENTORY`;
export const ON_REMOVE_INVENTORY = `${PREFIX}ON_REMOVE_INVENTORY`;
