export const PREFIX = "@@scene/";

export const ASYNC_SCENE_INIT = `${PREFIX}ASYNC_SCENE_INIT`;
export const INITIALIZE_SCENE = `${PREFIX}INITIALIZE_SCENE`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_ALL_SCENES_SUCCESS = `${PREFIX}GET_ALL_SCENES_SUCCESS`;
export const ON_CHANGE_SCENE_FIELD = `${PREFIX}ON_CHANGE_SCENE_FIELD`;
export const ON_ADD_NEW_LAYER = `${PREFIX}ON_ADD_NEW_LAYER`;

export const ON_SELECT_SINGLE_SCENE = `${PREFIX}ON_SELECT_SINGLE_SCENE`;
export const ON_ADD_NEW_STORY = `${PREFIX}ON_ADD_NEW_STORY`;
export const ON_CHANGE_STORY_FIELD = `${PREFIX}ON_CHANGE_STORY_FIELD`;
