export const PREFIX = "@@schedule/";

export const ASYNC_SCHEDULE_INIT = `${PREFIX}ASYNC_SCHEDULE_INIT`;
export const INITIALIZE_SCHEDULE = `${PREFIX}INITIALIZE_SCHEDULE`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_SCHEDULE_SUCCESS = `${PREFIX}GET_SCHEDULE_SUCCESS`;
export const ON_CHANGE_SCENE_NUMBER = `${PREFIX}ON_CHANGE_SCENE_NUMBER`;
