export const PREFIX = "@@script/";

export const ASYNC_SCRIPT_INIT = `${PREFIX}ASYNC_SCRIPT_INIT`;
export const INITIALIZE_SCRIPT = `${PREFIX}INITIALIZE_SCRIPT`;
export const HANDLE_NOTIFICATION = `${PREFIX}HANDLE_NOTIFICATION`;

export const GET_ALL_SCRIPTS_SUCCESS = `${PREFIX}GET_ALL_SCRIPTS_SUCCESS`;
